### ISSUE TITLE
Release Milestones

### ISSUE THREAD

**Issue by domicmeia** [domicmeia/gcp_practice#1]
### V0 
- [ ] Onboarding Documentation
- [ ] Simple API response (hello world!)
- [ ] Unit tests
- [ ] Running somewhere other than the dev machine
 
### V1
- [ ] Create translation endpoint
- [ ] Store translations in short-term storage
- [ ] Call existing service for translation
- [ ] Move towards long-term storage
